<a href="https://colab.research.google.com/github/anas1IA/2024_new_package/blob/main/PyTorch_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [166]:
import torch
import torch.nn as
import torch.optim as opt
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,StandardScaler
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, TensorDataset

In [167]:
!mkdir data_PyTorch

mkdir: cannot create directory ‘data_PyTorch’: File exists


In [168]:
!mv winequality-red.csv data_PyTorch/

mv: cannot stat 'winequality-red.csv': No such file or directory


In [169]:
!cd data_PyTorch/

In [170]:
!touch processing

In [171]:
!mkdir data_processing

mkdir: cannot create directory ‘data_processing’: File exists


In [172]:
!mv processing  data_processing/

**data**

In [173]:
data = "data_PyTorch/winequality-red.csv"

In [174]:
df  = pd.read_csv(data)

In [175]:
df.shape

(1599, 12)

In [176]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [177]:

# sns.pairplot(df)
# plt.show()

In [178]:
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, csv_file):
        self.data = pd.read_csv(csv_file)
        self.features = torch.tensor(self.data.iloc[:, :-1].values, dtype=torch.float32)
        self.targets = torch.tensor(self.data.iloc[:, -1].values, dtype=torch.long)

    def __len__(self):
        return len(self.data)
    def split_data(self):
      return self.features,self.targets

    def __getitem__(self, idx):
        return self.features[idx], self.targets[idx]

In [179]:
# Example usage:
csv_file = data
batch_size = 32

In [180]:
# Create custom dataset
dataset = CustomDataset(csv_file)
X,y = dataset.split_data()
# data1 =LabelEncoder.fit_transform(dataset)
# Create data loader
y = LabelEncoder().fit_transform(y)

In [181]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [193]:
X_train, X_test = torch.tensor(X_train, dtype=torch.float32), torch.tensor(X_test, dtype=torch.float32,requires_grad=True)
y_train, y_test = torch.tensor(y_train, dtype=torch.long), torch.tensor(y_test, dtype=torch.long)

<ipython-input-193-f1a54c42b108>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train, X_test = torch.tensor(X_train, dtype=torch.float32), torch.tensor(X_test, dtype=torch.float32,requires_grad=True)
<ipython-input-193-f1a54c42b108>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train, y_test = torch.tensor(y_train, dtype=torch.long), torch.tensor(y_test, dtype=torch.long)


In [194]:
X_train

tensor([[ 0.2183,  0.8897,  0.1921,  ...,  1.0935,  0.4582,  1.1232],
        [-1.2902, -1.7888,  0.6528,  ..., -0.4004, -0.4012,  1.4083],
        [ 1.4948, -0.7843,  1.0110,  ..., -0.0757,  0.5155, -0.5874],
        ...,
        [-0.6520,  0.4991, -1.0875,  ...,  1.2884, -0.6877, -0.8725],
        [-0.2458, -1.8446,  0.3968,  ...,  0.0542,  0.8020,  1.4083],
        [-1.4642, -1.3424, -0.0638,  ...,  0.5089, -0.6877,  2.9288]])

In [195]:
train_data = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_data, batch_size=64, shuffle=True)

In [203]:
import torch
import torch.nn as nn

import torch.nn.functional as F

class SimpleNN(nn.Module):
    def __init__(self, input_size, hidden_size1, hidden_size2, output_size):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size1)
        self.relu1 = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size1, hidden_size2)
        self.relu2 = nn.ReLU()
        self.fc3 = nn.Linear(hidden_size2, output_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.fc3(x)
        # Apply argmax to get the predicted class labels
        # _, predicted_labels = torch.max(x, 1)
        return F.softmax(x)

# Example usage



In [204]:
# Example usage:
# Define input size, hidden sizes, and output size
input_size = 11
hidden_size1 = 20
hidden_size2 = 15
output_size = 6  # 5 classes

In [205]:
# Create an instance of the model
model = SimpleNN(input_size, hidden_size1, hidden_size2, output_size)

In [206]:
# Define loss criterion (CrossEntropyLoss) and optimizer (e.g., SGD)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

# Generate some random input data (batch size 1, input size 10)
input_data = torch.randn(1, input_size)

# Forward pass through the model
output = model(input_data)

print(output)

tensor([[0.1678, 0.1699, 0.1463, 0.1216, 0.1811, 0.2133]],
       grad_fn=<SoftmaxBackward0>)


<ipython-input-203-82a11d62b014>:23: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(x)


In [207]:
output

tensor([[0.1678, 0.1699, 0.1463, 0.1216, 0.1811, 0.2133]],
       grad_fn=<SoftmaxBackward0>)

In [211]:
epoch =100
for i in range(epoch):
  model.train()
  for batch_features, batch_targets in train_loader:
    # Zero the gradients
    optimizer.zero_grad()

    # Forward pass
    outputs = model(batch_features)

    #print(outputs)
    # Apply softmax to convert logits to probabilities
    #probs = F.softmax(outputs, dim=1)
    #print(probs)
    # Compute loss using probabilities and target labels
    #loss = criterion(probs, batch_targets_tensor)

    # Compute loss
    loss = criterion(outputs, batch_targets)

    # Backward pass
    loss.backward()

    # Update weights
    optimizer.step()
  if
    # Print loss or any other metrics as desired
    print("Batch Loss:", loss.item())

Batch Loss: 1.8096044063568115
Batch Loss: 1.803592324256897
Batch Loss: 1.8138922452926636
Batch Loss: 1.8074569702148438
Batch Loss: 1.8091782331466675
Batch Loss: 1.8004218339920044
Batch Loss: 1.8089007139205933
Batch Loss: 1.8146748542785645
Batch Loss: 1.811350703239441
Batch Loss: 1.8087124824523926
Batch Loss: 1.8099652528762817
Batch Loss: 1.8165733814239502
Batch Loss: 1.8188161849975586
Batch Loss: 1.810508131980896
Batch Loss: 1.8133302927017212
Batch Loss: 1.8165534734725952
Batch Loss: 1.8142311573028564
Batch Loss: 1.809389352798462
Batch Loss: 1.8122246265411377
Batch Loss: 1.804480791091919


<ipython-input-203-82a11d62b014>:23: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(x)
